debug backend build

diff --git a/backend/Dockerfile.prod b/backend/Dockerfile.prod
--- a/backend/Dockerfile.prod
+++ b/backend/Dockerfile.prod
@@ -22,6 +22,8 @@ RUN npx prisma generate
 
 RUN npm run build
 
+
+
 # Stage 2: Production
 FROM node:20-slim AS runner
 
@@ -31,10 +33,13 @@ WORKDIR /usr/app
 ENV NODE_ENV=production
 
 COPY --from=builder /usr/app/package*.json ./
+COPY --from=builder /usr/app/prisma.config.ts ./
 COPY --from=builder /usr/app/node_modules ./node_modules
 COPY --from=builder /usr/app/dist ./dist
 COPY --from=builder /usr/app/prisma ./prisma
-COPY --from=builder /usr/app/prisma.config.ts ./
+
+
+RUN ls -la && test -f prisma.config.ts || (echo "Missing config!" && exit 1)
 
 USER node
 
